version: '3.9'

services:

  db:
    container_name: mysqlDB
    image: mysql:5.7
    tty: true
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/lib:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=marcos
      - MYSQL_PASSWORD=mysecret
      - MYSQL_DATABASE=teste
  
volumes:
  db-volume:
